services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sukrtya-api
    ports:
      - "8081:8080"
    environment:
      DB_IP: ${DB_IP}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
    volumes:
      - "${HOST_LOG_DIR}:/app/logs"
      - "${HOST_IMAGE_DIR}:/app/SukrtyaImages"