networks:
  sukrtya-network:
    driver: bridge
services:
  
  app:
    image: sukrtya-api:latest
    container_name: sukrtya-api
    ports:
      - "8081:8080"
    environment:
      - DB_IP=192.168.20.18
      - DB_PORT=5432
      - DB_NAME=SUkrtya
      - DB_USERNAME=postgres
      - DB_PASSWORD=Psmri@2024
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=sukrtya-api
      - SERVER_URL=https://sukrtya.api.shsbihar.in
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317/v1/traces  # ✅ Tracing ke liye
    networks:
      - sukrtya-network

    volumes:
      - /home/Sukrtya/logs:/app/logs                    # For logs
      - /home/Sukrtya/SukrtyaImages:/app/SukrtyaImages  # Persist SukrtyaImages folder outside the container