networks:
  sukrtya-network:
services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OpenTelemetry collector gRPC
      - "4318:4318"   # OpenTelemetry collector HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - sukrtya-network


  app:
    image: sukrtya-api:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.20.18:5432/SUkrtya
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Psmri@2024
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=sukrtya-api-app
    networks:
      - sukrtya-network

    volumes:
      - /home/Sukrtya/logs:/app/logs                    # For logs
      - /home/Sukrtya/SukrtyaImages:/app/SukrtyaImages  # Persist SukrtyaImages folder outside the container

