spring.application.name=sukrtya
server.port=8080
server.error.whitelabel.enabled=false

# PostgreSQL configuration
#spring.datasource.url=jdbc:postgresql://192.168.20.18:5432/SUkrtya
spring.datasource.url=jdbc:postgresql://115.245.54.213:5432/SUkrtya
spring.datasource.username=postgres
spring.datasource.password=Psmri@2024
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Log4j2 configuration
#logging.config=classpath:log4j2.yaml

 
tracing.url= http://localhost:4318/v1/traces
management.tracing.sampling.probability= 1.0
logging.pattern.level= '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

