#app.base.url=http://localhost:8080
spring.application.name=${SPRING_APPLICATION_NAME:sukrtya}
server.port=${SERVER_PORT:8080}
#server.error.whitelabel.enabled=false

# PostgreSQL configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.sukrtya.in:5432/SUkrtya}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Zltj6ghj6J}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
## Optional: JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# Logging configuration
logging.config=classpath:logback-spring.xml
logging.file.path=./logs
logging.file.name=./logs/sukrtya.log
logging.level.root=info
logging.level.com.piramal.sukrtya=DEBUG
logging.level.org.springframework=info

management.endpoints.web.exposure.include=health


# tracing.url=http://localhost:4318/v1/traces
# management.tracing.sampling.probability=1.0
# logging.pattern.level='%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
