spring.application.name=${SPRING_APPLICATION_NAME:sukrtya-api}
server.port=${SERVER_PORT:8080}
#server.error.whitelabel.enabled=false


# PostgreSQL configuration

spring.datasource.url=jdbc:postgresql://${DB_IP:115.245.54.213}:${DB_PORT:5432}/${DB_NAME:SUkrtya}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Psmri@2024}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
 

# Logging configuration
logging.config=classpath:logback-spring.xml
logging.file.path=./logs
logging.file.name=./logs/sukrtya.log
logging.level.root=info
logging.level.com.piramal.sukrtya=DEBUG
logging.level.org.springframework=info

management.endpoints.web.exposure.include=health

# OpenTelemetry Configuration
management.tracing.sampling.probability=1.0
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://host.docker.internal:55681/v1/traces}
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
logging.pattern.level='%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
